import folder_paths
from server import PromptServer
from comfy_execution.graph import ExecutionBlocker
from PIL import Image, ImageOps
import numpy as np
import torch
from comfy_execution.graph import ExecutionBlocker
class Compositor3Debug:
    """
    Debug node to inspect fabricData and imageName values
    """
    
    # Dictionary to cache config for each node instance, indexed by node_id
    configCache = {}
    
    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                
                "fabricData": ("STRING", {
                    "multiline": False,
                    "default": "",
                    "tooltip": "JSON string containing the compositor state (transforms, positions, visibility). Auto-managed by the compositor interface"
                }),
                "imageName": ("STRING", {
                    "multiline": False,
                    "default": "",
                    "tooltip": "Name of the snapshot image file. Auto-generated based on graph and node ID"
                }),
                #is it possible that if we put config on top then the gui breaks ?
                "config": ("COMPOSITOR_CONFIG", {"forceInput": True, "tooltip": "Configuration from CompositorConfig node containing canvas size, images, and settings"}),
            },
            "hidden": {
                "extra_pnginfo": "EXTRA_PNGINFO",
                "node_id": "UNIQUE_ID",
            },  
           
        }

    RETURN_TYPES = ("STRING", "STRING","IMAGE")
    RETURN_NAMES = ("fabricData_output", "imageName_output","image")
    OUTPUT_TOOLTIPS = ("Compositor state data (transforms, positions, etc.)", 
                       "Filename of the saved composition snapshot",
                       "Final composed image rendered from the compositor canvas")
    FUNCTION = "run"
    CATEGORY = "image/debug"
    DESCRIPTION = "Interactive compositor canvas for positioning, scaling, rotating, and arranging multiple images with real-time preview. Provides a visual editor with layers panel, alignment tools, and snap-to-grid functionality."
    OUTPUT_NODE = True

    def run(self, **kwargs):
        node_id = kwargs.get('node_id', None)

        config = kwargs.get('config', "default")
        fabricData = kwargs.get('fabricData', "default")
        imageName = kwargs.get('imageName', "default")
        padding = config["padding"]
        invertMask = config["invertMask"]
        width = config["width"]
        height = config["height"]
        config_node_id = config["node_id"]
        onConfigChanged = config["onConfigChanged"]
        names = config["names"]
        saveFolder = config.get("saveFolder", "output")
        configSignature = config.get("configSignature", None)

        # Detect if configuration has changed since last run for this specific node
        # Use the config signature (hash) generated by CompositorConfig3
        # This signature changes whenever ANY input changes (images, masks, parameters)
        cached_signature = self.configCache.get(node_id)
        configChanged = cached_signature != configSignature
        
        # Store the current signature using compositor node's ID as key
        self.configCache[node_id] = configSignature

        ui = {
            #"test": ("value",),
            "padding": [padding],
            "width": [width],
            "height": [height],
            "config_node_id": [config_node_id],
            "node_id": [node_id],
            "names": names,
            "fabricData": [fabricData],
            "configChanged": [configChanged],
            "onConfigChanged": [onConfigChanged],
            "saveFolder": [saveFolder],
        }

        detail = {"output": ui, "node": node_id}
        PromptServer.instance.send_sync("compositor_init", detail)

        # Check if imageName is valid (not default/empty)
        if not imageName or imageName == "default" or imageName.strip() == "":
            blocker_result = tuple([ExecutionBlocker(None)] * len(self.RETURN_TYPES))
            return {
                "ui": ui,
                "result": blocker_result
            }
        
        # Construct path based on saveFolder
        folder_path = f"../{saveFolder}/compositor/{imageName}"
        imageExists = folder_paths.exists_annotated_filepath(folder_path)
        if not imageExists:
            # Return ExecutionBlocker for all outputs if blocked
            blocker_result = tuple([ExecutionBlocker(None)] * len(self.RETURN_TYPES))
            return {
                "ui": ui,
                "result": blocker_result
            }
        image_path = folder_paths.get_annotated_filepath(folder_path)
        i = Image.open(image_path)
        i = ImageOps.exif_transpose(i)
        if i.mode == 'I':
            i = i.point(lambda i: i * (1 / 255))
        image = i.convert("RGB")
        image = np.array(image).astype(np.float32) / 255.0
        image = torch.from_numpy(image)[None, ]
        
        return (fabricData, imageName,image)
