import folder_paths
from server import PromptServer
from comfy_execution.graph import ExecutionBlocker
from PIL import Image, ImageOps
import numpy as np
import torch
from typing_extensions import override
from comfy_api.latest import ComfyExtension, io


class Compositor4(io.ComfyNode):
    """
    V4 compositor node with integrated mask handling
    """
    
    # Dictionary to cache config for each node instance, indexed by node_id
    configCache = {}
    
    @classmethod
    def define_schema(cls) -> io.Schema:
        return io.Schema(
            node_id="Compositor4",
            display_name="Compositor V4",
            category="image",
            description="Interactive compositor canvas for positioning, scaling, rotating, and arranging multiple images with real-time preview and mask support. Provides a visual editor with layers panel, alignment tools, and snap-to-grid functionality.",
            inputs=[
                io.String.Input("fabricData", default="", multiline=False, tooltip="JSON string containing the compositor state (transforms, positions, visibility). Auto-managed by the compositor interface"),
                io.String.Input("imageName", default="", multiline=False, tooltip="Name of the snapshot image file. Auto-generated based on graph and node ID"),
                io.Custom("COMPOSITOR_CONFIG").Input("config", tooltip="Configuration from CompositorConfig node containing canvas size, images, masks, and settings"),
            ],
            outputs=[
                io.String.Output(display_name="fabricData_output", tooltip="Compositor state data (transforms, positions, etc.)"),
                io.String.Output(display_name="imageName_output", tooltip="Filename of the saved composition snapshot"),
                io.Image.Output(display_name="image", tooltip="Final composed image rendered from the compositor canvas"),
                io.String.Output(display_name="transforms", tooltip="JSON transform data for Compositor4TransformsOut node"),
                io.Custom("COMPOSITOR_OUTPUT_MASKS").Output(display_name="layer_outputs", tooltip="Layer outputs (images and masks) for Compositor4MasksOutput node"),
            ],
            hidden=[
                io.Hidden.extra_pnginfo,
                io.Hidden.unique_id,
            ],
            is_output_node=True,
        )


    @classmethod
    def execute(cls, fabricData, imageName, config) -> io.NodeOutput:
        # Access hidden inputs via cls.hidden
        node_id = cls.hidden.unique_id if cls.hidden else None
        extra_pnginfo = cls.hidden.extra_pnginfo if cls.hidden else None
        
        print(f"[Compositor4] execute: node_id={node_id}, imageName={imageName}")
        
        fabricData = fabricData or "default"
        imageName = imageName or "default"
        
        # Handle config - it should be a dict from CompositorConfig4
        if not config or not isinstance(config, dict):
            print(f"[Compositor4] Config invalid or missing")
            # If config is missing or invalid, we can't proceed
            blocker_result = tuple([ExecutionBlocker(None)] * 5)  # V4: 5 outputs now
            ui = {"error": ["Config input required from CompositorConfig4 node"]}
            return io.NodeOutput(*blocker_result, ui=ui)
        
        padding = config.get("padding", 0)
        invertMask = config.get("invertMask", False)
        width = config.get("width", 512)
        height = config.get("height", 512)
        config_node_id = config.get("node_id")
        onConfigChangedContinue = config.get("onConfigChangedContinue", False)
        names = config.get("names", [])
        maskNames = config.get("maskNames", [])  # V4: Get mask filenames
        saveFolder = config.get("saveFolder", "output")
        configSignature = config.get("configSignature", None)

        # Detect if configuration has changed since last run for this specific node
        # Use the config signature (hash) generated by CompositorConfig4
        # This signature changes whenever ANY input changes (images, masks, parameters)
        cached_signature = cls.configCache.get(node_id)
        configChanged = cached_signature != configSignature
        
        print(f"[Compositor4] configChanged={configChanged}, onConfigChangedContinue={onConfigChangedContinue}")
        
        # Store the current signature using compositor node's ID as key
        cls.configCache[node_id] = configSignature

        ui = {
            #"test": ("value",),
            "padding": [padding],
            "width": [width],
            "height": [height],
            "config_node_id": [config_node_id],
            "node_id": [node_id],
            "names": names,
            "maskNames": maskNames,  # V4: Pass mask filenames to frontend
            "fabricData": [fabricData],
            "configSignature": [configSignature],
            "configChanged": [configChanged],
            "onConfigChangedContinue": [onConfigChangedContinue],
            "saveFolder": [saveFolder],
        }

        print(ui)

        detail = {"output": ui, "node": node_id}
        PromptServer.instance.send_sync("compositor4_init", detail)

        # when config changes, will always stop, frontend decides what to do next
        # this sends an executed event , with blocker
        if configChanged:
            blocker_result = tuple([ExecutionBlocker(None)] * 5)  # V4: 5 outputs now
            print(f"[Compositor4] Config changed, blocking execution for user interaction, user decides what to do next")
            return io.NodeOutput(*blocker_result, ui=ui)

        # Config hasn't changed - proceed to load existing image
        print(f"[Compositor4] Config unchanged, proceeding to load image")
        
        # Check if imageName is valid (not default/empty)
        if not imageName or imageName == "default" or imageName.strip() == "":
            print(f"[Compositor4] No valid imageName - this is first run or widget not set, blocking")
            blocker_result = tuple([ExecutionBlocker(None)] * 5)  # V4: 5 outputs now
            return io.NodeOutput(*blocker_result, ui=ui)
        
        # Construct path based on saveFolder
        folder_path = f"../{saveFolder}/compositor/{imageName}"
        imageExists = folder_paths.exists_annotated_filepath(folder_path)
        if not imageExists:
            # Return ExecutionBlocker for all outputs if blocked
            print(f"[Compositor4] Image not found: {folder_path}")
            blocker_result = tuple([ExecutionBlocker(None)] * 5)  # V4: 5 outputs now
            return io.NodeOutput(*blocker_result, ui=ui)
        image_path = folder_paths.get_annotated_filepath(folder_path)
        print(f"[Compositor4] Loading image: {image_path}")
        i = Image.open(image_path)
        i = ImageOps.exif_transpose(i)
        if i.mode == 'I':
            i = i.point(lambda i: i * (1 / 255))
        image = i.convert("RGB")
        image = np.array(image).astype(np.float32) / 255.0
        image = torch.from_numpy(image)[None, ]
        
        # V4: Prepare transforms output (JSON string for Compositor4TransformsOut)
        transforms_output = fabricData  # fabricData already contains the transforms JSON
        
        # V4: Prepare layer_outputs for Compositor4MasksOutput
        # This is a dict containing individual layer images and masks
        # For now, return empty structure - full implementation will extract layers from canvas
        layer_outputs = {
            "images": [],  # List of layer images as tensors
            "masks": []    # List of layer masks as tensors
        }
        
        print(f"[Compositor4] Returning image successfully with transforms and layer_outputs")
        return io.NodeOutput(fabricData, imageName, image, transforms_output, layer_outputs, ui=ui)


class Compositor4Extension(ComfyExtension):
    @override
    async def get_node_list(self) -> list[type[io.ComfyNode]]:
        return [Compositor4]


async def comfy_entrypoint() -> Compositor4Extension:
    return Compositor4Extension()
